- name: Install dependencies
  apt:
    pkg: ['python3', 'python3-dev', 'python3-pip', 'python-virtualenv', 'libssl-dev', 'openssl', 'libacl1-dev', 'libacl1', 'liblz4-dev', 'liblz4-1', 'build-essential']
    state: present

- name: Install borgbackup
  pip: 
    name: ['borgbackup==1.1.0'] 
    state: present
    executable: pip3
